//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHistory {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PureHistory.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created by eineboek ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;ARP&apos; prefix ähnelt.
        /// </summary>
        internal static string ArpeggioPrefix {
            get {
                return ResourceManager.GetString("ArpeggioPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Arpeggio Ships ähnelt.
        /// </summary>
        internal static string ArpeggioPrompt {
            get {
                return ResourceManager.GetString("ArpeggioPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;AL&apos; prefix ähnelt.
        /// </summary>
        internal static string AzurLanePrefix {
            get {
                return ResourceManager.GetString("AzurLanePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Azur Lane Ships ähnelt.
        /// </summary>
        internal static string AzurLanePrompt {
            get {
                return ResourceManager.GetString("AzurLanePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caution : Azur Lane ships have similar, but not identical performance to their regular counterparts. Replacing the ship name with the regular counterpart name could lead to a misjudgement of the battle situation. ähnelt.
        /// </summary>
        internal static string AzurLaneWarning {
            get {
                return ResourceManager.GetString("AzurLaneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Black Friday Ships ähnelt.
        /// </summary>
        internal static string BlackShipPrompt {
            get {
                return ResourceManager.GetString("BlackShipPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;B&apos; suffix ähnelt.
        /// </summary>
        internal static string BlackShipsSuffix {
            get {
                return ResourceManager.GetString("BlackShipsSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PureHistory cannot be installed to the specified path. ähnelt.
        /// </summary>
        internal static string CannotFindStructure {
            get {
                return ResourceManager.GetString("CannotFindStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the path to the desired World of Warships installation ähnelt.
        /// </summary>
        internal static string ClientSelection {
            get {
                return ResourceManager.GetString("ClientSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue ähnelt.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Dragon Ships ähnelt.
        /// </summary>
        internal static string DragonShipPrompt {
            get {
                return ResourceManager.GetString("DragonShipPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error has occured : ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error during installation. Please try again or contact the author. ähnelt.
        /// </summary>
        internal static string ErrorDuringInstallation {
            get {
                return ResourceManager.GetString("ErrorDuringInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Examples : ähnelt.
        /// </summary>
        internal static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press any key to exit the program ... ähnelt.
        /// </summary>
        internal static string ExitProgram {
            get {
                return ResourceManager.GetString("ExitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for HSF Harekaze ähnelt.
        /// </summary>
        internal static string HSFHarekazePrompt {
            get {
                return ResourceManager.GetString("HSFHarekazePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caution : HSF Harekaze is a unique ship capable of fitting multiple hulls with differing performance. Replacing the ship name with the regular counterpart name could lead to a misjudgement of the battle situation. ähnelt.
        /// </summary>
        internal static string HSFHarekazeWarning {
            get {
                return ResourceManager.GetString("HSFHarekazeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;HSF&apos; prefix ähnelt.
        /// </summary>
        internal static string HSFPrefix {
            get {
                return ResourceManager.GetString("HSFPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for HSF Graf Spee ähnelt.
        /// </summary>
        internal static string HSFSpeePrompt {
            get {
                return ResourceManager.GetString("HSFSpeePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation is completed. ähnelt.
        /// </summary>
        internal static string InstallationComplete {
            get {
                return ResourceManager.GetString("InstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Response. ähnelt.
        /// </summary>
        internal static string InvalidResponse {
            get {
                return ResourceManager.GetString("InvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Lima (ASUS Collaboration) ships ähnelt.
        /// </summary>
        internal static string LimaShipPrompt {
            get {
                return ResourceManager.GetString("LimaShipPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;Lima&apos; suffix ähnelt.
        /// </summary>
        internal static string LimaShipsSuffix {
            get {
                return ResourceManager.GetString("LimaShipsSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace custom flag with pan-asian flag ähnelt.
        /// </summary>
        internal static string LunarNewYearFlagOption1 {
            get {
                return ResourceManager.GetString("LunarNewYearFlagOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace custom flag with flag of respective country ähnelt.
        /// </summary>
        internal static string LunarNewYearFlagOption2 {
            get {
                return ResourceManager.GetString("LunarNewYearFlagOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Lunar New Year Ships ähnelt.
        /// </summary>
        internal static string LunarNewYearPrompt {
            get {
                return ResourceManager.GetString("LunarNewYearPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;ST&apos; suffix of Alabama ST ähnelt.
        /// </summary>
        internal static string MiscAlabamaOption1 {
            get {
                return ResourceManager.GetString("MiscAlabamaOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Update description for distinguishment ähnelt.
        /// </summary>
        internal static string MiscAlabamaOption2 {
            get {
                return ResourceManager.GetString("MiscAlabamaOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Replace Ship preview ähnelt.
        /// </summary>
        internal static string MiscAlabamaOption3 {
            get {
                return ResourceManager.GetString("MiscAlabamaOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;B&apos; suffix of Arkansas Beta ähnelt.
        /// </summary>
        internal static string MiscArkansasSuffix {
            get {
                return ResourceManager.GetString("MiscArkansasSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miscellaneous settings ähnelt.
        /// </summary>
        internal static string MiscellaneousPrompt {
            get {
                return ResourceManager.GetString("MiscellaneousPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;A&apos; suffix of Iwaki Alpha ähnelt.
        /// </summary>
        internal static string MiscIwakiSuffix {
            get {
                return ResourceManager.GetString("MiscIwakiSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;R&apos; suffix of Kamikaze R ähnelt.
        /// </summary>
        internal static string MiscKamikazeOption1 {
            get {
                return ResourceManager.GetString("MiscKamikazeOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Update description for distinguishment ähnelt.
        /// </summary>
        internal static string MiscKamikazeOption2 {
            get {
                return ResourceManager.GetString("MiscKamikazeOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Replace Ship preview ähnelt.
        /// </summary>
        internal static string MiscKamikazeOption3 {
            get {
                return ResourceManager.GetString("MiscKamikazeOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove the &apos;1941&apos; from West Virginia 1941 ähnelt.
        /// </summary>
        internal static string MiscWestVirginiaName {
            get {
                return ResourceManager.GetString("MiscWestVirginiaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die World of Warships ModStation was found. Please install this mod after using the ModStation, as the ModStation will override all other mod files. ähnelt.
        /// </summary>
        internal static string ModStationWarning {
            get {
                return ResourceManager.GetString("ModStationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PureHistory Version 1.0.1 ähnelt.
        /// </summary>
        internal static string ModVersion {
            get {
                return ResourceManager.GetString("ModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrow Keys up/down for movement ähnelt.
        /// </summary>
        internal static string NavigationHelp1 {
            get {
                return ResourceManager.GetString("NavigationHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrow Key right to toggle an option ähnelt.
        /// </summary>
        internal static string NavigationHelp2 {
            get {
                return ResourceManager.GetString("NavigationHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ENTER to continue to the next page ähnelt.
        /// </summary>
        internal static string NavigationHelp3 {
            get {
                return ResourceManager.GetString("NavigationHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is this path correct? ähnelt.
        /// </summary>
        internal static string PathCorrection {
            get {
                return ResourceManager.GetString("PathCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press any key to continue ... ähnelt.
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace custom flag ähnelt.
        /// </summary>
        internal static string ReplaceFlag {
            get {
                return ResourceManager.GetString("ReplaceFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ship preview ähnelt.
        /// </summary>
        internal static string ReplacePreview {
            get {
                return ResourceManager.GetString("ReplacePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ship name with respective class name ähnelt.
        /// </summary>
        internal static string ReplaceShipNameClassName {
            get {
                return ResourceManager.GetString("ReplaceShipNameClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ship name with regular counterpart ähnelt.
        /// </summary>
        internal static string ReplaceShipNameCounterpart {
            get {
                return ResourceManager.GetString("ReplaceShipNameCounterpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace sillouette ähnelt.
        /// </summary>
        internal static string ReplaceSillouette {
            get {
                return ResourceManager.GetString("ReplaceSillouette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Language : ähnelt.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press any key to start the mod installation ... ähnelt.
        /// </summary>
        internal static string StartInstallation {
            get {
                return ResourceManager.GetString("StartInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Update ship description for distinguishment in port ähnelt.
        /// </summary>
        internal static string UpdateDescription {
            get {
                return ResourceManager.GetString("UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Warhammer 40.000 ships ähnelt.
        /// </summary>
        internal static string WarhammerPrompt {
            get {
                return ResourceManager.GetString("WarhammerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die World of Warships does not seem to be installed at the specified path. Continue installation regardless? ähnelt.
        /// </summary>
        internal static string WOWSNotFound {
            get {
                return ResourceManager.GetString("WOWSNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die World of Warships Version 0.10.1 ähnelt.
        /// </summary>
        internal static string WOWSVersion {
            get {
                return ResourceManager.GetString("WOWSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
