//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHistory {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PureHistory.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die already exists in the mod folder. Should it be overwritten? ähnelt.
        /// </summary>
        internal static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;ARP&apos; prefix ähnelt.
        /// </summary>
        internal static string ArpeggioPrefix {
            get {
                return ResourceManager.GetString("ArpeggioPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Arpeggio Ships ähnelt.
        /// </summary>
        internal static string ArpeggioTitle {
            get {
                return ResourceManager.GetString("ArpeggioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;AL&apos; prefix ähnelt.
        /// </summary>
        internal static string AzurLanePrefix {
            get {
                return ResourceManager.GetString("AzurLanePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Azur Lane Ships ähnelt.
        /// </summary>
        internal static string AzurLaneTitle {
            get {
                return ResourceManager.GetString("AzurLaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caution : Azur Lane ships have similar, but not identical performance to their regular counterparts.
        ///Replacing the ship name with the regular counterpart name could lead to a misjudgement of the battle situation. ähnelt.
        /// </summary>
        internal static string AzurLaneWarning {
            get {
                return ResourceManager.GetString("AzurLaneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;B&apos; suffix ähnelt.
        /// </summary>
        internal static string BlackShipsSuffix {
            get {
                return ResourceManager.GetString("BlackShipsSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Black Friday Ships ähnelt.
        /// </summary>
        internal static string BlackShipTitle {
            get {
                return ResourceManager.GetString("BlackShipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PureHistory cannot be installed to the specified path. ähnelt.
        /// </summary>
        internal static string CannotFindStructure {
            get {
                return ResourceManager.GetString("CannotFindStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the path to the desired World of Warships installation ähnelt.
        /// </summary>
        internal static string ClientSelectionTitle {
            get {
                return ResourceManager.GetString("ClientSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue ähnelt.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created by eineboek ähnelt.
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Dragon Ships ähnelt.
        /// </summary>
        internal static string DragonShipTitle {
            get {
                return ResourceManager.GetString("DragonShipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The installation path can&apos;t be empty. Please try again. ähnelt.
        /// </summary>
        internal static string EmptyPath {
            get {
                return ResourceManager.GetString("EmptyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press any key to exit the program ... ähnelt.
        /// </summary>
        internal static string ExitProgramAnyKey {
            get {
                return ResourceManager.GetString("ExitProgramAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file ähnelt.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error has occured : ähnelt.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for HSF Harekaze ähnelt.
        /// </summary>
        internal static string HSFHarekazeTitle {
            get {
                return ResourceManager.GetString("HSFHarekazeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caution : HSF Harekaze is a unique ship capable of fitting multiple hulls with differing performance.
        ///Replacing the ship name with the regular counterpart name (Kagerō) could lead to a misjudgement of the battle situation. ähnelt.
        /// </summary>
        internal static string HSFHarekazeWarning {
            get {
                return ResourceManager.GetString("HSFHarekazeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;HSF&apos; prefix ähnelt.
        /// </summary>
        internal static string HSFPrefix {
            get {
                return ResourceManager.GetString("HSFPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for HSF Graf Spee ähnelt.
        /// </summary>
        internal static string HSFSpeeTitle {
            get {
                return ResourceManager.GetString("HSFSpeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error during installation. Please try again or contact the author. ähnelt.
        /// </summary>
        internal static string InstallationError {
            get {
                return ResourceManager.GetString("InstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation is finished ähnelt.
        /// </summary>
        internal static string InstallationFinished {
            get {
                return ResourceManager.GetString("InstallationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ask for each file independently ähnelt.
        /// </summary>
        internal static string InstallationSettingsAskForEach {
            get {
                return ResourceManager.GetString("InstallationSettingsAskForEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t overwrite any existing files ähnelt.
        /// </summary>
        internal static string InstallationSettingsNoOverwrite {
            get {
                return ResourceManager.GetString("InstallationSettingsNoOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite all conflicting files ähnelt.
        /// </summary>
        internal static string InstallationSettingsOverwriteAll {
            get {
                return ResourceManager.GetString("InstallationSettingsOverwriteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation settings ähnelt.
        /// </summary>
        internal static string InstallationSettingsTitle {
            get {
                return ResourceManager.GetString("InstallationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Response. ähnelt.
        /// </summary>
        internal static string InvalidResponse {
            get {
                return ResourceManager.GetString("InvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;Lima&apos; suffix ähnelt.
        /// </summary>
        internal static string LimaShipsSuffix {
            get {
                return ResourceManager.GetString("LimaShipsSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Lima (ASUS Collaboration) ships ähnelt.
        /// </summary>
        internal static string LimaShipTitle {
            get {
                return ResourceManager.GetString("LimaShipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ship preview background flag with flag of respective country ähnelt.
        /// </summary>
        internal static string LunarNewYearFlagOptionOriginal {
            get {
                return ResourceManager.GetString("LunarNewYearFlagOptionOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ship preview background flag with pan-asian flag ähnelt.
        /// </summary>
        internal static string LunarNewYearFlagOptionPanasia {
            get {
                return ResourceManager.GetString("LunarNewYearFlagOptionPanasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Lunar New Year Ships ähnelt.
        /// </summary>
        internal static string LunarNewYearTitle {
            get {
                return ResourceManager.GetString("LunarNewYearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;ST&apos; suffix of Alabama ST ähnelt.
        /// </summary>
        internal static string MiscAlabamaSuffix {
            get {
                return ResourceManager.GetString("MiscAlabamaSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;B&apos; suffix of Arkansas Beta ähnelt.
        /// </summary>
        internal static string MiscArkansasSuffix {
            get {
                return ResourceManager.GetString("MiscArkansasSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miscellaneous settings ähnelt.
        /// </summary>
        internal static string MiscellaneousTitle {
            get {
                return ResourceManager.GetString("MiscellaneousTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;A&apos; suffix of Iwaki Alpha ähnelt.
        /// </summary>
        internal static string MiscIwakiSuffix {
            get {
                return ResourceManager.GetString("MiscIwakiSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &apos;R&apos; suffix of Kamikaze R ähnelt.
        /// </summary>
        internal static string MiscKamikazeSuffix {
            get {
                return ResourceManager.GetString("MiscKamikazeSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove the &apos;1941&apos; from West Virginia 1941 ähnelt.
        /// </summary>
        internal static string MiscWestVirginiaName {
            get {
                return ResourceManager.GetString("MiscWestVirginiaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die World of Warships ModStation was found.
        ///Please install this mod after using the ModStation, as the ModStation will override all other mod files. ähnelt.
        /// </summary>
        internal static string ModStationWarning {
            get {
                return ResourceManager.GetString("ModStationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PureHistory Version 1.1.0 ähnelt.
        /// </summary>
        internal static string ModVersion {
            get {
                return ResourceManager.GetString("ModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrow Keys left/right to move to the previous/next page ähnelt.
        /// </summary>
        internal static string NavigationHelpArrowHorizontal {
            get {
                return ResourceManager.GetString("NavigationHelpArrowHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrow Keys up/down for movement between options ähnelt.
        /// </summary>
        internal static string NavigationHelpArrowVertical {
            get {
                return ResourceManager.GetString("NavigationHelpArrowVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ENTER to toggle/select an option ähnelt.
        /// </summary>
        internal static string NavigationHelpEnter {
            get {
                return ResourceManager.GetString("NavigationHelpEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is this path correct? ähnelt.
        /// </summary>
        internal static string PathCorrection {
            get {
                return ResourceManager.GetString("PathCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified path can&apos;t be found. Please try again. ähnelt.
        /// </summary>
        internal static string PathDoesntExist {
            get {
                return ResourceManager.GetString("PathDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Examples : ähnelt.
        /// </summary>
        internal static string PathFormatExamples {
            get {
                return ResourceManager.GetString("PathFormatExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press any key to continue ... ähnelt.
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully copied file ähnelt.
        /// </summary>
        internal static string ProgressString1 {
            get {
                return ResourceManager.GetString("ProgressString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die to ähnelt.
        /// </summary>
        internal static string ProgressString2 {
            get {
                return ResourceManager.GetString("ProgressString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ProgressString3 {
            get {
                return ResourceManager.GetString("ProgressString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ship preview ähnelt.
        /// </summary>
        internal static string ReplacePreview {
            get {
                return ResourceManager.GetString("ReplacePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ship preview background flag ähnelt.
        /// </summary>
        internal static string ReplacePreviewBg {
            get {
                return ResourceManager.GetString("ReplacePreviewBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die • Replace ship preview ähnelt.
        /// </summary>
        internal static string ReplacePreviewMisc {
            get {
                return ResourceManager.GetString("ReplacePreviewMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ship name with respective class name ähnelt.
        /// </summary>
        internal static string ReplaceShipNameClassName {
            get {
                return ResourceManager.GetString("ReplaceShipNameClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ship name with regular counterpart ähnelt.
        /// </summary>
        internal static string ReplaceShipNameCounterpart {
            get {
                return ResourceManager.GetString("ReplaceShipNameCounterpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace sillhouette in battle overview ähnelt.
        /// </summary>
        internal static string ReplaceSillouette {
            get {
                return ResourceManager.GetString("ReplaceSillouette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Language / Sprache auswählen : ähnelt.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press left arrow key to go back ähnelt.
        /// </summary>
        internal static string StartInstallationNoticeGoBack {
            get {
                return ResourceManager.GetString("StartInstallationNoticeGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press ENTER to start the mod installation ... ähnelt.
        /// </summary>
        internal static string StartInstallationNoticeStart {
            get {
                return ResourceManager.GetString("StartInstallationNoticeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die • Update ship description for distinction in port ähnelt.
        /// </summary>
        internal static string UpdateDescription {
            get {
                return ResourceManager.GetString("UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings for Warhammer 40.000 ships ähnelt.
        /// </summary>
        internal static string WarhammerTitle {
            get {
                return ResourceManager.GetString("WarhammerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caution : Warhammer 40.000 ships have similar, but not identical performance to their regular counterparts (Amagi).
        ///Replacing the ship name with the regular counterpart could lead to a misjudgement of the battle situation. ähnelt.
        /// </summary>
        internal static string WarhammerWarning {
            get {
                return ResourceManager.GetString("WarhammerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die World of Warships does not seem to be installed at the specified path. Continue installation regardless? ähnelt.
        /// </summary>
        internal static string WoWsNotFound {
            get {
                return ResourceManager.GetString("WoWsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die World of Warships Version 0.10.1 ähnelt.
        /// </summary>
        internal static string WoWsVersion {
            get {
                return ResourceManager.GetString("WoWsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
